name: ci workflow
# evento PULL_REQUEST
on:
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
      # Steps importante para poder gerar o docker e gerar os build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      #Subir imagem para o Container Registry: DOCKERHUB
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        #Uso IF aqui para usar em outro STEP
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # Repositorio
          tags: mrogerius/fc2.0-ci-go:latest
      